# Site settings
title: 'Unicloudus'
email: 'bob8unicloudus'
description: > # this means to ignore newlines until "baseurl:"
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://unicloudus.github.io' # the base hostname & protocol for your site

twitter_username: 'unicloudus'
github_username: 'unicloudus'

# Build settings
markdown: kramdown

